authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from authentication import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('password_resset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_resset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('schedule.urls', namespace='schedule')),
    path('', include('journal.urls', namespace='journal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'

urlpatterns = [
    path('journal/', views.journal, name='journal'),
    path('add_mark/', views.add_mark, name='add_mark'),
    path('view_grades/', views.grades_view, name='view_grades'),
]

schedule/urls.py
from django.urls import path
from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('schedule/', views.schedule_view, name='schedule'),
    path('session_schedule/', views.session_schedule_view, name='session_schedule_view'),
]

schedule/models.py
from django.utils import timezone
from django.db import models
from authentication.models import User, Group
from authentication.enum import Groups


class TeacherManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(groups__name=Groups.TEACHER.name)

    class Meta:
        verbose_name_plural = 'Группы студентов'
        verbose_name = 'Группы студентов'


class Subject(models.Model):
    name = models.CharField("Название предмета", max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Предметы студентов'
        verbose_name = 'Предметы студентов'


class Schedule(models.Model):
    DAYS_OF_WEEK = [
        ('monday', 'Понедельник'),
        ('tuesday', 'Вторник'),
        ('wednesday', 'Среда'),
        ('thursday', 'Четверг'),
        ('friday', 'Пятница'),
        ('saturday', 'Суббота')
    ]
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name="Название группы", default=None)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name="Название предмета", default=None)
    day_of_week = models.CharField('День недели', choices=DAYS_OF_WEEK, max_length=150)
    date = models.DateField(default=timezone.now)
    number = models.IntegerField("Номер пары", null=True)
    time_from = models.TimeField("Начало пары", null=True)
    time_to = models.TimeField("Конец пары", null=True)
    type_of_lesson = models.CharField('Вид занятий', max_length=150, null=True)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Преподаватель',
                                limit_choices_to={'role': Groups.TEACHER.name})
    place_of_perfomance = models.CharField('Место проведение', max_length=150, null=True)
    type_schedule = models.ForeignKey('schedule.ScheduleType', on_delete=models.CASCADE,
                                      verbose_name='Вид рассписания')
    session_number = models.ForeignKey('schedule.Session', on_delete=models.CASCADE, verbose_name='Номер сессии',
                                       default=None)

    def __str__(self):
        return f"{self.type_of_lesson} - {self.subject} - {self.teacher}"

    class Meta:
        verbose_name_plural = 'Расписание студентов'
        verbose_name = 'Расписание студентов'


class ScheduleType(models.Model):
    LESSON = 'Предмет'
    SESSION = 'Сессия'
    TYPE_CHOICES = [
        (LESSON, 'Предмет'),
        (SESSION, 'Сессия'),
    ]
    schedule_type = models.CharField('Тип расписания', max_length=10, choices=TYPE_CHOICES)

    class Meta:
        verbose_name_plural = 'Типы расписания'
        verbose_name = 'Тип расписания'

    def __str__(self):
        return self.schedule_type


class Session(models.Model):
    TYPE_CHOICES = [
        (1, 'Первый семестр'),
        (2, 'Второй семестр'),
        (3, 'Третий семестр'),
        (4, 'Четвертый семестр'),
        (5, 'Пятый семестр'),
        (6, 'Шестой семестр'),
        (7, 'Седьмой семестр'),
        (8, 'Восьмой семестр')
    ]

    session_number = models.IntegerField('Номер сессии', choices=TYPE_CHOICES, max_length=10, unique=True)

    def __str__(self):
        return f"{self.session_number} - семестр"

    class Meta:
        verbose_name_plural = 'Сессия'
        verbose_name = 'Сессия'

schedule/views.py
from django.shortcuts import render
from schedule.models import Schedule, Session
from django.contrib.auth.decorators import login_required


@login_required
def schedule_view(request):
    schedule_data = {}
    groups = Schedule.objects.filter(type_schedule__schedule_type='Предмет').values_list('group__name', flat=True).distinct()
    days_of_week = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    day_names = dict(Schedule.DAYS_OF_WEEK)

    for group in groups:
        group_schedule = Schedule.objects.filter(group__name=group, type_schedule__schedule_type='Предмет').order_by('day_of_week', 'number')
        schedule_data[group] = {day: [] for day in days_of_week}
        for schedule in group_schedule:
            schedule_data[group][schedule.day_of_week.lower()].append({
                'number': schedule.number,
                'time_from': schedule.time_from,
                'time_to': schedule.time_to,
                'subject': schedule.subject,
                'type_of_lesson': schedule.type_of_lesson,
                'teacher': schedule.teacher.get_full_name() if schedule.teacher else 'N/A',
                'place_of_performance': schedule.place_of_perfomance,
            })

    active_day = request.GET.get('day')
    if not active_day:
        active_day = days_of_week[0]
    active_schedules = {group: schedules.get(active_day, []) for group, schedules in schedule_data.items()}

    context = {
        'schedule_data': schedule_data,
        'day_names': day_names,
        'active_day': active_day,
        'active_schedules': active_schedules,
    }

    return render(request, 'schedule/schedule.html', context)



@login_required
def session_schedule_view(request):
    day_names = dict(Session.TYPE_CHOICES)
    selected_semester = request.GET.get('semester', next(iter(day_names)))

    session_schedule = Schedule.objects.filter(type_schedule__schedule_type='Сессия', session_number=selected_semester)

    context = {
        'session_schedule': session_schedule,
        'day_names': day_names,
        'selected_semester': selected_semester,
    }

    return render(request, 'schedule/session_schedule.html', context)

schedule/templates/schedule/schedule.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Расписание занятий</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            background-color: #337ab7;
            padding: 10px;
            border-radius: 5px;
            color: #fff;
        }

        .left-header {
            flex: 1;
            display: flex;
            justify-content: flex-start;
        }

        .right-header {
            display: flex;
            justify-content: flex-end;
        }

        .header a, .header button {
            text-decoration: none;
            color: #fff;
            margin-right: 10px;
        }

        .logout-button, .grades-button {
            background-color: #d9534f;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 16px;
            border-radius: 5px;
            border: none;
            cursor: pointer;
        }

        .logout-button:hover, .grades-button:hover {
            background-color: #c9302c;
        }

        .grades-button {
            background-color: #5bc0de;
        }

        .grades-button:hover {
            background-color: #31b0d5;
        }

        .schedule-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
            background-color: #fff;
        }

        .schedule-table th, .schedule-table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: center;
            font-size: 16px;
        }

        .schedule-table th {
            background-color: #337ab7;
            font-weight: bold;
            color: #fff;
        }

        .schedule-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .schedule-table tr:hover {
            background-color: #e9e9e9;
        }

        .group-name {
            font-weight: bold;
            text-align: center;
            margin-bottom: 10px;
            font-size: 24px;
            color: #337ab7;
        }

        .day__filter {
            padding: 6px 10px;
            border: 1px solid #337ab7;
            border-radius: 8px;
            background-color: #fff;
            color: #337ab7;
            cursor: pointer;
            margin-right: 10px;
            font-size: 16px;
        }

        .day__filter:hover {
            background-color: #337ab7;
            color: #fff;
        }

        .days__filter {
            display: flex;
            justify-content: center;
            margin: 15px 0;
        }

        .day__filter.active {
            background-color: #337ab7;
            color: #fff;
        }

    </style>
</head>
<body>
    <div class="header">
        <div class="left-header">
            <button onclick="window.location.href='{% url 'schedule:schedule' %}'" class="grades-button">Просмотреть расписание</button>
            <button onclick="window.location.href='{% url 'journal:view_grades' %}'" class="grades-button">Просмотреть оценки</button>
            <button onclick="window.location.href='{% url 'schedule:session_schedule_view' %}'" class="grades-button">Расписание сессии</button>
        </div>
        <div class="right-header">
            <a href="{% url 'authentication:logout' %}" class="logout-button">Выйти</a>
        </div>
    </div>

    {% for group, schedule in schedule_data.items %}
    <div class="group-name">{{ user.get_full_name }}</div>
    <div class="days__filter">
        {% for day, name in day_names.items %}
            <button class="day__filter" data-day="{{ day|lower }}">{{ name }}</button>
        {% endfor %}
    </div>
    <table class="schedule-table">
        <thead>
            <tr>
                <th>№</th>
                <th>Время занятий</th>
                <th>Наименование дисциплин</th>
                <th>Вид занятий</th>
                <th>Ф.И.О преподавателя</th>
                <th>Место проведения</th>
            </tr>
        </thead>
        <tbody id="schedule-{{ group }}">
            {% for day, lessons in schedule.items %}
                {% for lesson in lessons %}
                    <tr data-day="{{ day|lower }}">
                        <td>{{ lesson.number }}</td>
                        <td>{{ lesson.time_from }} - {{ lesson.time_to }}</td>
                        <td>{{ lesson.subject }}</td>
                        <td>{{ lesson.type_of_lesson }}</td>
                        <td>{{ lesson.teacher }}</td>
                        <td>{{ lesson.place_of_performance }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var firstButton = document.querySelector('.day__filter');
            if (firstButton) {
                firstButton.classList.add('active');
                filterLessonsByDay(firstButton.dataset.day);
            }
        });

        document.querySelectorAll('.day__filter').forEach(function(button) {
            button.addEventListener('click', function() {
                document.querySelectorAll('.day__filter').forEach(function(btn) {
                    btn.classList.remove('active');
                });
                this.classList.add('active');
                filterLessonsByDay(this.dataset.day);
            });
        });

        function filterLessonsByDay(day) {
            document.querySelectorAll('tbody tr').forEach(function(row) {
                if (row.dataset.day === day) {
                    row.style.display = 'table-row';
                } else {
                    row.style.display = 'none';
                }
            });
        }
    </script>
</body>
</html>

schedule/templates/schedule/session_schedule.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Расписание сессии</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            background-color: #337ab7;
            padding: 10px;
            border-radius: 5px;
            color: #fff;
        }

        .left-header {
            flex: 1;
            display: flex;
            justify-content: flex-start;
        }

        .right-header {
            display: flex;
            justify-content: flex-end;
        }

        .header a, .header button {
            text-decoration: none;
            color: #fff;
            margin-right: 10px;
        }

        .logout-button, .grades-button {
            background-color: #d9534f;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            font-size: 16px;
            border-radius: 5px;
            border: none;
            cursor: pointer;
        }

        .logout-button:hover, .grades-button:hover {
            background-color: #c9302c;
        }

        .grades-button {
            background-color: #5bc0de;
        }

        .grades-button:hover {
            background-color: #31b0d5;
        }

        .semester-buttons {
            margin-bottom: 20px;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
        }

        .semester-button {
            background-color: #337ab7;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            margin: 5px;
            cursor: pointer;
            text-align: center;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }

        .semester-button:hover {
            background-color: #286090;
        }

        .schedule-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
            background-color: #fff;
        }

        .schedule-table th, .schedule-table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: center;
            font-size: 16px;
        }

        .schedule-table th {
            background-color: #337ab7;
            font-weight: bold;
            color: #fff;
        }

        .schedule-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .schedule-table tr:hover {
            background-color: #e9e9e9;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="left-header">
            <a href="{% url 'schedule:schedule' %}" class="grades-button">Просмотреть расписание</a>
        </div>
        <div class="right-header">
            <a href="{% url 'authentication:logout' %}" class="logout-button">Выйти</a>
        </div>
    </div>

    <h1>Расписание сессии</h1>
    <div class="semester-buttons">
        {% for key, value in day_names.items %}
            <button class="semester-button" onclick="filterBySemester('{{ key }}')">{{ value }}</button>
        {% endfor %}
    </div>
    <table class="schedule-table">
        <thead>
            <tr>
                <th>Тип сдачи</th>
                <th>День недели</th>
                <th>Время</th>
                <th>Предмет</th>
                <th>Преподаватель</th>
                <th>Место проведения</th>
            </tr>
        </thead>
        <tbody>
            {% for session in session_schedule %}
            <tr>
                <td>{{ session.type_of_lesson }}</td>
                <td>{{ session.get_day_of_week_display }}</td>
                <td>{{ session.time_from }} - {{ session.time_to }}</td>
                <td>{{ session.subject }}</td>
                <td>{{ session.teacher }}</td>
                <td>{{ session.place_of_perfomance }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function filterBySemester(semester) {
            const url = new URL(window.location.href);
            url.searchParams.set('semester', semester);
            window.location.href = url.toString();
        }
    </script>
</body>
</html>